@url_dev=http://127.0.0.1:3056/v1/api/

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: aaaaaaaaa

{
    "name": "Shop Hint",
    "email": "hint91@gmail.com",
    "password": "abc123"
}